myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from.import views

app_name ='myapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.add_new, name='add_new'),
    path('<int:id>/update/', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

    path('login/', views.login_req, name='login'),

    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('signup/', views.sign_up1, name='signup'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls', namespace= 'myapp')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class mymodel(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)

    material = models.CharField(max_length=100)

    msg = models.TextField(100)

    pics = models.FileField(upload_to='image/', max_length=100, null=True, blank=True)



    def __str__(self):
        return self.name

myapp/forms.py
from django import forms
from .models import *

class myform(forms.ModelForm):
    class Meta:
        model = mymodel
        fields = "__all__"

myapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse ,HttpResponseRedirect
from. models import mymodel
from .forms import myform
from django.contrib.auth import authenticate ,logout, login
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

# Create your views here.

app_name ='myapp'

def home(request):
    all_model = mymodel.objects.all()
    return render(request, 'myapp/home.html',{'all_model': all_model})

def detail(request,id):
    sanu = mymodel.objects.get(id=id)
    return render(request, 'myapp/detail.html',{'sanu':sanu})

def add_new(request):
    if request.method == 'POST':
        form = myform(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('/')
    else:
        form = myform()
    return render(request, 'myapp/add_new.html', {'form':form})



def update(request, id):
    treasure = get_object_or_404(mymodel, pk=id)

    if request.method == "POST":
        form = myform(request.POST, request.FILES, instance=treasure)
        if form.is_valid():
            form.save()

            return redirect( 'myapp:detail', id=treasure.pk)

    else:
        form = myform(instance=treasure)

        return render(request,'myapp/update.html', {'form': form})




def delete(request,id):
    obj = get_object_or_404(mymodel, id=id)
    if request.method == "POST":

        obj.delete()
        return redirect('/')

    return render(request, 'myapp/delete.html')


def login_req(request):

    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username =form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/')
    else:
        form=AuthenticationForm()
        return render(request,'registration/login.html',{'form':form})



def sign_up1(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()
            login(request,user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/sign_up.html', {'form': form})

def logout1(request):
    logout(request)
    return redirect('/')

myapp/templates/myapp/add_new.html
{% extends 'myapp/base.html' %}


{%block a%}


<h1>Add New </h1>
<p>
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>
</p>


{%endblock%}

myapp/templates/myapp/base.html
<html>
<body>

<a href="{% url 'myapp:home'%}">HOME PAGE</a>

{%block a%}
{%endblock%}

</body>
</html>

myapp/templates/myapp/delete.html
<p>
<h1>Delete form </h1>

<form method="POST" enctype="multipart/form-data" class="img-responsive">
    {% csrf_token %}
    {{form.as_p}}

    Are you want to delete this item
    <button type="submit">Yes</button>
    <a href="/">Cancel</a>
</form>
</p>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{%block a%}



{%load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
<p>
    <a href="{% url 'myapp:update' sanu.id%}">Edit Form</a><br>
    <a href="{% url 'myapp:home' %}">Home page</a>
    <a href="{% url 'myapp:delete' sanu.id%}">Delete</a><br>

</p>
<h2>danoshhhh</h2>
<h1>hello tabish</h1>

<h1> This is our detail pages </h1>
<p>
    {{sanu.name}}<br>
    {{sanu.Value}}<br>
    {{sanu.course}}<br>
    {{sanu.msg}}<br><br><br><br><br><br>
   {% if sanu.pics %}
    <img src="{{ sanu.pics.url}}" class="img-responsive">
    {% endif %}
    <a href="/">Back</a>
</p>


{%endblock%}

myapp/templates/myapp/home.html
{% extends 'myapp/base.html'%}

{%block a%}

<h1> WEELCOME IN OUR HOME PAGE</h1>


{% load static %}
<link rel="stylesheet"type="text/css" href="{% static 'myapp/style.css' %}">

{% if user.is_authenticated %}

<a href="{% url 'myapp:add_new' %}">Add New</a><br>
<li>{{user.username}}</li>
<li><a href="{% url 'myapp:logout' %}">Logout </a></li><br>

{% else %}

<li><a href="{% url 'myapp:login' %}">Login</a></li><br>
<li><a href="{% url 'myapp:signup' %}">Signup</a></li><br>


{% endif %}



<p>

{% for sanu in all_model %}
<li>
    <a href="/{{sanu.id}}">
    {{sanu.name}}<br><br></a>
    {{sanu.user}}
    {{sanu.id}}
     {% if sanu.pics %}
     <img src="{{sanu.pics.url}}" class="img-responsive">
     {% endif %}


</li>


{% endfor %}
<p/>

{%endblock%}

myapp/templates/myapp/update.html
{% extends 'myapp/base.html' %}
{%block a%}


<h1>Edit form </h1>

<form method="POST" enctype="multipart/form-data" class="img-responsive">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>
</p>

{%endblock%}